export const ADDTEACHER_REQUEST = "ADDTEACHER_REQUEST";
export const ADDTEACHER_SUCCESS = "ADDTEACHER_SUCCESS";
export const ADDTEACHER_FAILURE = "ADDTEACHER_FAILURE";

export const GETTEACHERS_REQUEST = "GETTEACHERS_REQUEST";
export const GETTEACHERS_SUCCESS = "GETTEACHERS_SUCCESS";
export const GETTEACHERS_FAILURE = "GETTEACHERS_FAILURE";

export const GETSTUDENTS_REQUEST = "GETSTUDENTS_REQUEST";
export const GETSTUDENTS_SUCCESS = "GETSTUDENTS_SUCCESS";
export const GETSTUDENTS_FAILURE = "GETSTUDENTS_FAILURE";

export const GETQUIZES_REQUEST = "GETQUIZES_REQUEST";
export const GETQUIZES_SUCCESS = "GETQUIZES_SUCCESS";
export const GETQUIZES_FAILURE = "GETQUIZES_FAILURE";

export const GETCOURSES_REQUEST = "GETCOURSES_REQUEST";
export const GETCOURSES_SUCCESS = "GETCOURSES_SUCCESS";
export const GETCOURSES_FAILURE = "GETCOURSES_FAILURE";

export const GETQUIZRESULTS_REQUEST = "GETQUIZRESULTS_REQUEST";
export const GETQUIZRESULTS_SUCCESS = "GETQUIZRESULTS_SUCCESS";
export const GETQUIZRESULTS_FAILURE = "GETQUIZRESULTS_FAILURE";

export const GETSTUDENTRESULTS_REQUEST = "GETSTUDENTRESULTS_REQUEST";
export const GETSTUDENTRESULTS_SUCCESS = "GETSTUDENTRESULTS_SUCCESS";
export const GETSTUDENTRESULTS_FAILURE = "GETSTUDENTRESULTS_FAILURE";
