export const GETCOURSES_REQUEST = "GETCOURSES_REQUEST";
export const GETCOURSES_SUCCESS = "GETCOURSES_SUCCESS";
export const GETCOURSES_FAILURE = "GETCOURSES_FAILURE";

export const GETQUIZES_REQUEST = "GETQUIZES_REQUEST";
export const GETQUIZES_SUCCESS = "GETQUIZES_SUCCESS";
export const GETQUIZES_FAILURE = "GETQUIZES_FAILURE";

export const GETQUIZ_REQUEST = "GETQUIZ_REQUEST";
export const GETQUIZ_SUCCESS = "GETQUIZ_SUCCESS";
export const GETQUIZ_FAILURE = "GETQUIZ_FAILURE";

export const ATTEMPTQUIZ_REQUEST = "ATTEMPTQUIZ_REQUEST";
export const ATTEMPTQUIZ_SUCCESS = "ATTEMPTQUIZ_SUCCESS";
export const ATTEMPTQUIZ_FAILURE = "ATTEMPTQUIZ_FAILURE";

export const GETALLRESULTS_REQUEST = "GETALLRESULTS_REQUEST";
export const GETALLRESULTS_SUCCESS = "GETALLRESULTS_SUCCESS";
export const GETALLRESULTS_FAILURE = "GETALLRESULTS_FAILURE";

export const ANTICHEAT_REQUEST = "ANTICHEAT_REQUEST";
export const ANTICHEAT_SUCCESS = "ANTICHEAT_SUCCESS";
export const ANTICHEAT_FAILURE = "ANTICHEAT_FAILURE";
