export const ADDCOURSE_REQUEST = "ADDCOURSE_REQUEST";
export const ADDCOURSE_SUCCESS = "ADDCOURSE_SUCCESS";
export const ADDCOURSE_FAILURE = "ADDCOURSE_FAILURE";

export const ADDSTUDENT_REQUEST = "ADDSTUDENT_REQUEST";
export const ADDSTUDENT_SUCCESS = "ADDSTUDENT_SUCCESS";
export const ADDSTUDENT_FAILURE = "ADDSTUDENT_FAILURE";

export const ADDQUIZ_SUCCESS = "ADDQUIZ_SUCCESS";
export const ADDQUIZ_FAILURE = "ADDQUIZ_FAILURE";
export const ADDQUIZ_REQUEST = "ADDQUIZ_REQUEST";

export const ENROLLSTUDENTS_REQUEST = "ENROLLSTUDENTS_REQUEST";
export const ENROLLSTUDENTS_SUCCESS = "ENROLLSTUDENTS_SUCCESS";
export const ENROLLSTUDENTS_FAILURE = "ENROLLSTUDENTS_FAILURE";

export const GETTEACHERCOURSES_REQUEST = "GETTEACHERCOURSES_REQUEST";
export const GETTEACHERCOURSES_SUCCESS = "GETTEACHERCOURSES_SUCCESS";
export const GETTEACHERCOURSES_FAILURE = "GETTEACHERCOURSES_FAILURE";

export const GETSTUDENTS_REQUEST = "GETSTUDENTS_REQUEST";
export const GETSTUDENTS_SUCCESS = "GETSTUDENTS_SUCCESS";
export const GETSTUDENTS_FAILURE = "GETSTUDENTS_FAILURE";

export const GETCOURSEQUIZES_REQUEST = "GETCOURSEQUIZES_REQUEST";
export const GETCOURSEQUIZES_SUCCESS = "GETCOURSEQUIZES_SUCCESS";
export const GETCOURSEQUIZES_FAILURE = "GETCOURSEQUIZES_FAILURE";

export const GETQUIZRESULTS_REQUEST = "GETQUIZRESULTS_REQUEST";
export const GETQUIZRESULTS_SUCCESS = "GETQUIZRESULTS_SUCCESS";
export const GETQUIZRESULTS_FAILURE = "GETQUIZRESULTS_FAILURE";

export const GETSTUDENTRESULTS_REQUEST = "GETSTUDENTRESULTS_REQUEST";
export const GETSTUDENTRESULTS_SUCCESS = "GETSTUDENTRESULTS_SUCCESS";
export const GETSTUDENTRESULTS_FAILURE = "GETSTUDENTRESULTS_FAILURE";
