export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const PRESISTLOGIN_REQUEST = "PRESISTLOGIN_REQUEST";
export const PRESISTLOGIN_SUCCESS = "PRESISTLOGIN_SUCCESS";
export const PRESISTLOGIN_FAILURE = "PRESISTLOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
